apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorization-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authorization-server
  template:
    metadata:
      labels:
        app: authorization-server
    spec:
      containers:
        - name: authorization-server
          image: mcubasgr/authorization-server:latest
          ports:
            - containerPort: 9000
          env:
            - name: CLIENT_URL
              valueFrom:
                configMapKeyRef:
                  name: authorization-server
                  key: client_url









