apiVersion: v1
kind: Secret
metadata:
  name: students-service
type: Opaque
data:
  db_username: cG9zdGdyZXM=
  db_password: cG9zdGdyZXM=

---

apiVersion: v1
kind: Secret
metadata:
  name: courses-service
type: Opaque
data:
  db_username: cm9vdA==
  db_password: cm9vdA==